[package]
authors = ["Mathias Hall-Andersen <mathias@hall-andersen.dk>"]
edition = "2018"
name = "reverie"
version = "0.2.0"

[dependencies]
async-channel = "*"
async-scoped = "0.4.1"
async-std = "*"
async-stream = "0.2.1"
bincode = "1.3.1"
blake3 = "0.3.4"
cpuprofiler = {version = "*", optional = true}
crossbeam = "0.7.3"
fnv = "1.0.7"
hex = "0.4"
rand = "0.7.3"
rand_core = "*"
rayon = "1.3"
serde = {version = "1.0", features = ["derive"]}
static_assertions = "1.1.0"

[dev-dependencies]
aes = "0.3.2"

[features]
profiler = ["cpuprofiler"]
