[package]
name = "zk-proof"
version = "0.1.0"
authors = ["Mathias Hall-Andersen <mathias@hall-andersen.dk>"]
edition = "2018"

[dependencies]
blake3 = "0.3.4" # used for Fiat-Shamir
aes = "0.3.2"    # used as PRF
typenum = "1.12.0"
serde = { version = "1.0", features = ["derive"] }
subtle = "2.2.3"
hex = "0.4"
rand = "0.7.3"