name: nightly

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master

      - name: Set nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2020-08-01
            override: true

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
